# Generated by Django 6.0.3 on 2026-04-16 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('learnapp', '0002_alter_userdetails_userpic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab_Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empId', models.IntegerField()),
                ('qualification', models.CharField(max_length=200)),
                ('years_of_exp', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.CharField(choices=[('CBC', 'CBC'), ('LFT', 'LFT'), ('urine total test', 'Urine Total Test'), ('urine microscopic', 'Urine Microscopic'), ('serum routine', 'Serum Routine'), ('thyroid', 'Thyroid')], default='CBC', max_length=200)),
                ('lab_result', models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_range', models.CharField(choices=[('Nil', 'Nil'), ('positive', 'Positive'), ('negative', 'Negative'), ('abnormal', 'Abnormal')], default='Nil', max_length=200)),
                ('result_desc', models.TextField()),
                ('test_cost', models.IntegerField()),
                ('pateint_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnapp.userdetails')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
    ]
