# Generated by Django 6.0.3 on 2026-04-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labreport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab_test',
            old_name='pateint_name',
            new_name='patient_name',
        ),
    ]
