# Generated by Django 6.0.3 on 2026-04-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALLDOCTORS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialisation', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Ortho', 'Ortho'), ('ENT', 'ENT'), ('Eye Specialist', 'Eye Specialist'), ('Dentist', 'Dentist'), ('Others', 'Others')])),
                ('experience', models.PositiveIntegerField()),
                ('licence_no', models.CharField(max_length=100, unique=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates')),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Ortho', 'Ortho'), ('ENT', 'ENT'), ('Eye Specialist', 'Eye Specialist'), ('Dentist', 'Dentist'), ('Others', 'Others')], max_length=50)),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('9AM-11AM', '9AM-11AM'), ('11AM-1PM', '11AM-1PM'), ('2PM-4PM', '2PM-4PM'), ('4PM-6PM', '4PM-6PM')], max_length=20)),
                ('consultation_charge', models.PositiveIntegerField(default=550)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.alldoctors')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.treatment')),
            ],
        ),
    ]
