# Generated by Django 6.0.3 on 2026-04-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='userimg'),
        ),
    ]
